Repository green-api/whatsapp-api-client-python, pull requests merged in 2023-11, with the labels that each got.

#36 Fixed ruff
  .github/workflows/python-package.yml
Labels: bug

#35 Sw 2544
  README.md
  README_RUS.md
  examples/sendPoll.py
  tests/test_methods.py
  whatsapp_api_client_python/tools/sending.py
Labels: documentation, enhancement

#37 Added Python 3.12 support
  .github/workflows/python-package.yml
  setup.py
Labels: enhancement

#38 SW-2059: add getWaSettings
  tests/test_methods.py
  whatsapp_api_client_python/tools/account.py
Labels: enhancement

#39 v0.0.43
  README.md
  docs/README.md
  examples/createGroupAndSendMessage.py
  examples/data/green-api-logo_2.png
  examples/data/rates.png
  examples/receiveNotification.py
  examples/sendPictureByLink.py
  examples/sendPictureByUpload.py
  examples/sendPoll.py
  examples/sendTextMessage.py
  examples/uploadFileAndSendFileByUrl.py
  tests/test_methods.py
  whatsapp_api_client_python/API.py
  whatsapp_api_client_python/tools/sending.py
Labels: documentation, enhancement

#40 Added method getAuthorizationCode
  README.md
  docs/README.md
  tests/test_methods.py
  whatsapp_api_client_python/tools/account.py
Labels: documentation, enhancement

#42 Added GetAuthorizationCode method
  README.md
  docs/README.md
  tests/test_methods.py
  whatsapp_api_client_python/tools/account.py
Labels: documentation, enhancement
